### ISSUE TITLE
comparison with https://github.com/msoucy/dproto ?

### ISSUE THREAD

**Issue by timotheecour** [dcarp/protobuf-upstream#5]
@msoucy
I'd like to knwo how the 2 projects compare in terms of feature set? Some kind of doc (or anything) would be nice

**Comment by dcarp** [comment]
The projects have different goals. This project is meant to be merged upstream. `dproto` mixes protocol buffer files into D code at compile time.

Excluding the differences between `proto3` and `proto2` like: oneof fields, all fields optional, map fields, etc. the main differences of the 2 projects are:

|  | protobuf | dproto |
| --- | --- | --- |
| version | `proto3` | `proto2` |
| implementation status | in progress | released |
| probuf compiler | protoc (upstream) | own compiler in D |
| compile-time `.proto` compiler | no | yes |
| JSON | yes | yes (own JSON representation) |
| [well-known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) | yes | no |
| conformance tested | yes | no |

**Comment by msoucy** [comment]
It appears that you haven't examined dproto enough. It uses painlessjson for its json support. I'm not sure what you mean by "well known types", as it utilises D's built in types, and though it's missing some higher-level tests (mainly for parsing) there are many tests in place to enforce serialization compatibility. (I also wouldn't count proto2/3 in that table, as despite having several betas there isn't a "stable" proto3 release yet)

Ultimately, as you said, the projects have different ideas about the best way to do it - the same method as for other languages, by integrating it upstream, vs integrating it more idiomatically at the cost of being slightly behind in features.

**Comment by dcarp** [comment]
@msoucy I updated the table regarding the JSON support and added a link to the well-known type description.
Please note that my changes work "just" with `proto3` and I don't intend to add `proto2` support later. This makes the design much simpler. Although `proto3` is not released yet, I think that the specification is stable enough and I hope that the D support will be ready on time for the first stable release.
